language: node_js
node_js:
- '12'
env:
  global:
  - secure: uUYGYOmx4REx16z5TyaZknc80Of1DHZmIz08RalGu7DM8mj1AqojTc05X4rFT/7p98HIyg+H2/2MSAE860ZOjIu8j6xeAgP2hqPEyIzai1OvOzgoJBNarLPVwFSgWut5nTUJ12YaFhUP/sm15aktcK9B0z/k1wXfYeSfwFu25qn7qpurP8TPAI3h6CKIk8zif0pILCZ+/lMWIWcNSU61dyrvxcuGOyspPYXfkbfOJW3INR2fI3QMc0ShYtq12b3QiZ8+2mSEZq8CbU8Hlxd6kXiJZ+2vNqcAv4J6ooF1RvH4HP7TXi/M8p9DSTjlRbA3s4O2YT+FMy3tOzy6Qx/EE3vkX+tQMkGpL/7mbLu4vBgjf+5p3TXtzZLwX1Aan2XGvItGMIt0Bq1HlLL1sw9V7qfwMh4ArLfu3lYr93a9ZhuueO58t198v+IMSKRNKyA2mObzP0HgTEjwNmWbzA6C0IQm7R8zPIZDIvDhiCSzQblHxWKGS69oD+XIeYteACZWF2IAL0RQ8z0d8Rz6krVA6OqFPiAx2Kmcqmk8qqWmSGDnXZIExo90Y3ex5YxsBFNOCjZ/Amr+94Z1pedEF/jgVpjz0NPPLedXo+qsg9eGI6lE7wTIslBk77ZGezMJFU9TlCyRObsR8AVkrGjF4rwqOGbDXVwiDBHwQHQXLIq9hfc=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_035836d9af95_key -iv $encrypted_035836d9af95_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
